### ISSUE TITLE
how can i do remote rooming and reserving i can t seem to figure it out and i tried placing the flags and it doesn t work pls help

### ISSUE THREAD

**Issue by DragonFire12** [edhaase/ScreepsAI#1]

**Comment by edhaase** [comment]
At the time of writing remote operations are handled by specific flag colors, and scouts will place flags if the correct values are set in memory to both spawn scouts, and enable remote mining. 

This may change someday, as the primary focus has been on flexibility. Surviving under all kinds of scenarios. Remote mining is currently not necessary for this to operate and in certain cases of contention can actually hold it back.
